# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: ToyDIM
email: melro-leandro@gmx.com

#write html inside the double quotes to display in jumbotron
description: "<h1>A library of MATLAB tools  used to simulate the dynamic behavior of a rigid and flexible body system with arbitrary topology.
</h1>"

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://melroleandro.github.io" # the base hostname & protocol for your site
twitter_username: MelroLeandro
github_username:  MelroLeandro

# Build settings
markdown: kramdown
