title: Toydim
description: A library of MATLAB tools used to simulate the dynamic behavior of a rigid and flexible body system with arbitrary topology.
google_analytics: 
show_downloads: true
theme: jekyll-theme-cayman

gems:
  - jekyll-mentions
